# Generated by Django 3.0.4 on 2020-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
