# Generated by Django 3.0.4 on 2020-04-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0002_cutting_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=100)),
                ('fabric_name', models.CharField(max_length=100)),
                ('cutting_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
