# Generated by Django 3.0.4 on 2020-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
