# Generated by Django 3.0.4 on 2020-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(),
        ),
    ]
