# Generated by Django 3.0.4 on 2020-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0009_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='level',
            field=models.CharField(default='Cutting', max_length=100),
            preserve_default=False,
        ),
    ]
