# Generated by Django 3.0.4 on 2020-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0011_packing_sewing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=10)),
                ('fabric_name', models.CharField(max_length=100)),
                ('cutting_type', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
