# Generated by Django 3.0.4 on 2020-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0012_billing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billing',
            new_name='Invoice',
        ),
    ]
