# Generated by Django 3.0.4 on 2020-04-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0013_auto_20200415_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='bill_no',
            new_name='invoice_no',
        ),
    ]
